try {
    hello();
} catch (error) {
    console.log(error)
}

try {
    anotherFuntion();
} catch (error) {
    console.log('Esto es un error!');
}